language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script:
  - mvn clean verify 
   - mvn clean install -U
branches:
  only:
    - develop

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
 